Bugfix/single notizia
italia/design-comuni-wordpress-theme pull request #134
Opened 2022-11-30 15:47 UTC by marcelloscanavino

aggiunta sezione "dataset" nel template notizia

2022-12-02 08:31 UTC, zetareticoli requested changes
Tutti i titoli di tipo `<h4>` per le sezioni della pagina devono diventare `<h2 class="mb-3">`

2022-12-02 08:31 UTC, zetareticoli commented on single-notizia.php
> +                        <h4 id="descrizione">Descrizione</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-02 08:31 UTC, zetareticoli commented on single-notizia.php
> +                        <h4 id="documenti">Documenti</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-02 08:31 UTC, zetareticoli commented on single-notizia.php
> +                        <h4 id="allegati">Allegati</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-02 08:31 UTC, zetareticoli commented on single-notizia.php
> +                        <h4 id="a-cura-di">A cura di</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-05 22:29 UTC, astagi commented
@marcelloscanavino ci sono alcune segnalazioni di @zetareticoli da sistemare prima del merge

2022-12-13 11:28 UTC, zetareticoli approved these changes

2022-12-13 11:28 UTC, zetareticoli commented
@astagi rinviamo le modifiche su `<h4>` perché stiamo rivedendo i mockup e lo stile associato. si può procedere con _merge_

2022-12-13 17:53 UTC, merged