Template single-persona_pubblica
italia/design-comuni-wordpress-theme pull request #422
Opened 2024-03-11 09:34 UTC by fabricius4

Mi scuso per la poca conoscenza di php che può far risultare il codice scritto male o non proprio armonioso.  Ma in considerazione del fatto che ad oggi non esiste un template ufficiale, il mio vuole solo essere di spunto per successive revisioni e miglioramenti. Anticipo che non sono riuscito a inserire la visualizzazione degli incarichi.

## Descrizione

## Checklist

- [ ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ ] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2024-03-12 17:22 UTC, zetareticoli reviewed
Puoi allegare uno screen de template completo?

2024-03-13 07:44 UTC, fabricius4 commented
![Uploading template persona.jpg…]()

2024-03-13 07:45 UTC, fabricius4 commented
> Puoi allegare uno screen de template completo?

![template persona](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/405d9a85-1360-4340-8faf-8fc7de97ceb0)

2024-03-19 16:27 UTC, zetareticoli requested changes
Sicuramente è un punto di partenza, ma sarebbe raccomandato seguire il layout [disponibile in Figma](https://www.figma.com/community/file/1262690210012419806/comuni-modello-sito-e-servizi)

Nella pagina Figma Community puoi vedere l'anteprima navigando le pagine.

2024-05-16 09:34 UTC, astagi commented
@fabricius4 procediamo il lavoro sulla PR https://github.com/italia/design-comuni-wordpress-theme/pull/426 che segue le linee guida da Figma. Grazie comunque del contributo!

2024-05-16 09:34 UTC, closed without merging