Template "tutti i luoghi"
italia/design-comuni-wordpress-theme pull request #434
Opened 2024-06-06 05:20 UTC by totolabs

Realizzato il nuovo template per "Tutti i luoghi".

## Descrizione

Nel dettaglio:

- aggiunto il template "Tutti i luoghi"
https://comune.totolabs.it/vivere-il-comune/luoghi/
- aggiunta la scheda "Luoghi" nel pannello di configurazione del tema", con possibilità di impostare immagine/banner e didascali "hero" e luoghi in evidenza
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/109132513/82417d74-65b3-45a2-a3e1-3153822c00a3)
- aggiunte le relative card previste per una corretta visualizzazione dei luoghi
- aggiunta la pagina "I luoghi" tra le pagine predefinite, la quale utilizza il template creato
- modificato il collegamento nella pagina "Vivere il comune" del pulsante "Tutti i luoghi" con l'aggiunta della nuova pagina
https://comune.totolabs.it/vivere-il-comune/

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2024-06-10 13:15 UTC, zetareticoli reviewed
Ottimo lavoro @totolabs 

Ho un solo dubbio relativo alla possibilità di caricare un banner per la pagina lista. Per quale motivo lo hai previsto?

2024-06-11 08:13 UTC, zetareticoli requested changes

2024-06-11 08:13 UTC, zetareticoli commented on inc/admin/options/pagina_luoghi.php
> +        'desc' => __( 'Immagine/ banner (in alto nella pagina)' , 'design_comuni_italia' ),
```suggestion
        'desc' => __( 'Immagine di copertina della pagina (opzionale)' , 'design_comuni_italia' ),
```

2024-06-12 10:26 UTC, astagi approved these changes

2024-06-12 10:26 UTC, merged